package org.osrs.util;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;

public class AccountManager extends javax.swing.JFrame {

	/**
	 * Creates new form AccountManager
	 */
	public AccountManager() {
		try{
			FileReader reader = new FileReader("accounts.dat");
			BufferedReader bReader = new BufferedReader(reader);
			for(Object o : bReader.lines().toArray()){
				String s = (String)o;
				String[] sa = s.split(":");
				Data.loadedAccounts.add(new Account(sa[0], sa[1], Boolean.parseBoolean(sa[2])));
			}
			bReader.close();
		}
		catch(Exception e){
			
		}
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		accountListContainer = new javax.swing.JList<String>();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		usernameField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		passwordField = new javax.swing.JTextField();
		isMembers = new javax.swing.JCheckBox();
		addAccountButton = new javax.swing.JButton();
		editAccountButton = new javax.swing.JButton();
		deleteAccountButton = new javax.swing.JButton();
		useSelectedAccountButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
		String[] names = new String[Data.loadedAccounts.size()+1];
		names[0]="-No Account-";
		int i=1;
		for(Account ac : Data.loadedAccounts){
			names[i]=ac.getUsername();
			i++;
		}
		accountListContainer.setModel(new javax.swing.AbstractListModel<String>() {
			private static final long serialVersionUID = 1L;
			String[] strings = names;
			public int getSize() { return strings.length; }
			public String getElementAt(int i) { return strings[i]; }
		});
		accountListContainer.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				accountListContainerValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(accountListContainer);

		jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
		jLabel1.setText("Account Manager");

		jLabel2.setText("Username : ");

		jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
		jLabel3.setText("Account Information");

		usernameField.setText("");

		jLabel4.setText("Password : ");

		passwordField.setText("");

		isMembers.setText("Is Members");

		addAccountButton.setText("Add");
		addAccountButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addAccountButtonActionPerformed(evt);
			}
		});

		editAccountButton.setText("Edit");
		editAccountButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editAccountButtonActionPerformed(evt);
			}
		});

		deleteAccountButton.setText("Delete");
		deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteAccountButtonActionPerformed(evt);
			}
		});

		useSelectedAccountButton.setText("Use Selected Account");
		useSelectedAccountButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				useSelectedAccountButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(10, 10, 10)
										.addComponent(useSelectedAccountButton))
										.addComponent(jLabel1)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel3)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(17, 17, 17)
																				.addComponent(jLabel2)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																				.addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(isMembers)
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(jLabel4)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
																								.addGroup(layout.createSequentialGroup()
																										.addComponent(addAccountButton)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(deleteAccountButton)))))
																										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel3)
										.addGap(6, 6, 6)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(isMembers)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(addAccountButton)
																.addComponent(editAccountButton)
																.addComponent(deleteAccountButton)))
																.addComponent(jScrollPane1))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(useSelectedAccountButton)
																.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {
		try{
			Account add = null;
			for(Account ac : Data.loadedAccounts){
				if(ac.getUsername().equals(usernameField.getText())){
					add=ac;
					break;
				}
			}
			if(add==null){
				Data.loadedAccounts.add(new Account(usernameField.getText(), passwordField.getText(), isMembers.isSelected()));
				FileWriter fileWriter = new FileWriter("accounts.dat");
				BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
				for(Account ac : Data.loadedAccounts){
					bufferedWriter.write(""+ac.getUsername()+":");
					bufferedWriter.write(""+ac.getPassword()+":");
					bufferedWriter.write(""+ac.isMembers());
					bufferedWriter.newLine();
				}
				bufferedWriter.close();
				String[] names = new String[Data.loadedAccounts.size()+1];
				names[0]="-No Account-";
				int i=1;
				for(Account ac : Data.loadedAccounts){
					names[i]=ac.getUsername();
					i++;
				}
				accountListContainer.setListData(names);
			}
			usernameField.setText("");
			passwordField.setText("");
			isMembers.setSelected(false);
			accountListContainer.clearSelection();
		}
		catch(Exception e){
			e.printStackTrace();
		}
	}                                                
	private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {       
		try{
			Account edit = null;
			for(Account ac : Data.loadedAccounts){
				if(ac.getUsername().equals(usernameField.getText())){
					edit=ac;
					break;
				}
			}
			if(edit!=null){
				//Username shouldnt ever change, and therefore should be deleted/readded in that case
				edit.setPassword(passwordField.getText());
				edit.setMembers(isMembers.isSelected());
				FileWriter fileWriter = new FileWriter("accounts.dat");
				BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
				for(Account ac : Data.loadedAccounts){
					bufferedWriter.write(""+ac.getUsername()+":");
					bufferedWriter.write(""+ac.getPassword()+":");
					bufferedWriter.write(""+ac.isMembers());
					bufferedWriter.newLine();
				}
				bufferedWriter.close();
			}
			usernameField.setText("");
			passwordField.setText("");
			isMembers.setSelected(false);
			accountListContainer.clearSelection();
		}
		catch(Exception e){
			e.printStackTrace();
		}
	}                                                 
	private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {   
		try{
			Account remove = null;
			for(Account ac : Data.loadedAccounts){
				if(ac.getUsername().equals(usernameField.getText())){
					remove=ac;
					break;
				}
			}
			if(remove!=null){
				Data.loadedAccounts.remove(remove);
				FileWriter fileWriter = new FileWriter("accounts.dat");
				BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
				for(Account ac : Data.loadedAccounts){
					bufferedWriter.write(""+ac.getUsername()+":");
					bufferedWriter.write(""+ac.getPassword()+":");
					bufferedWriter.write(""+ac.isMembers());
					bufferedWriter.newLine();
				}
				bufferedWriter.close();
				String[] names = new String[Data.loadedAccounts.size()+1];
				names[0]="-No Account-";
				int i=1;
				for(Account ac : Data.loadedAccounts){
					names[i]=ac.getUsername();
					i++;
				}
				accountListContainer.setListData(names);
			}
			usernameField.setText("");
			passwordField.setText("");
			isMembers.setSelected(false);
			accountListContainer.clearSelection();
		}
		catch(Exception e){
			e.printStackTrace();
		}
	}                                                   
	private void useSelectedAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {    
		if(accountListContainer.getSelectedIndex()>0){
			String value = accountListContainer.getSelectedValue();
			Account get = null;
			for(Account ac : Data.loadedAccounts){
				if(ac.getUsername().equals(value)){
					get=ac;
					break;
				}
			}
			if(get!=null){
				Data.currentContext.loginHandler.setLoginInfo(get.getUsername(), get.getPassword());
				Data.currentContext.loginHandler.membersAccount=get.isMembers();
				this.setVisible(false);
			}
		}
	}                                                        
	private void accountListContainerValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                  
		if(accountListContainer.getSelectedIndex()>0){
			String value = accountListContainer.getSelectedValue();
			Account get = null;
			for(Account ac : Data.loadedAccounts){
				if(ac.getUsername().equals(value)){
					get=ac;
					break;
				}
			}
			if(get!=null){
				usernameField.setText(get.getUsername());
				passwordField.setText(get.getPassword());
				isMembers.setSelected(get.isMembers());
			}
		}
		else{
			usernameField.setText("");
			passwordField.setText("");
			isMembers.setSelected(false);
		}
	}                                                 
	private javax.swing.JList<String> accountListContainer;
	private javax.swing.JButton addAccountButton;
	private javax.swing.JButton deleteAccountButton;
	private javax.swing.JButton editAccountButton;
	private javax.swing.JCheckBox isMembers;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField passwordField;
	private javax.swing.JButton useSelectedAccountButton;
	private javax.swing.JTextField usernameField;
}