package org.osrs.api.wrappers;

import java.awt.Point;
import java.lang.management.GarbageCollectorMXBean;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import org.osrs.api.objects.MenuAction;
import org.osrs.util.MultiboxHandler;

public interface Client extends GameShell{
	/**
	 * Used for ignoring disabled rendering.
	 * Only works with objects, not npcs/players.
	 */
	public ArrayList<Long> renderEntities = new ArrayList<Long>();

	public Inflater inflater();
	public ByteBuffer cacheBuffer();
	public ByteBuffer responseHeaderBuffer();
	public ByteBuffer responseArchiveBuffer();
	public Producer producer();
	public HashTable componentTable();
	public HashTable widgetFlags();
	public HashTable netPendingWrites();
	public HashTable netPendingPriorityResponses();
	public HashTable netPendingResponses();
	public HashTable netPendingPriorityWrites();
	public HashTable itemContainers();
	public FixedSizeDeque chatlineMessages();
	public NodeList classInfoList();
	public DoublyNode chatlineMessageNodeList();
	public ClientPreferences preferences();
	public Queue netPendingWritesQueue();
	public Cache objectDefinitionCache();
	public Cache objectModelHeaderCache();
	public Cache objectBaseModelCache();
	public Cache objectAnimatedModelCache();
	public Cache playerModelCache();
	public Cache inventoryDefinitionCache();
	public Cache npcDefinitionCache();
	public Cache npcModelCache();
	public Cache combatBarSpriteCache();
	public Cache widgetSpriteCache();
	public Cache widgetBufferedImageCache();
	public Cache widgetModelCache();
	public Cache widgetFontCache();
	public Cache varPlayerTypeCache();
	public Cache spotAnimCache();
	public Cache spotAnimModelCache();
	public Cache animationSequenceCache();
	public Cache animationSkeletonsCache();
	public Cache itemSpriteCache();
	public Cache itemDefinitionCache();
	public Cache itemModelCache();
	public OutgoingPacketMeta OUTGOING_PACKET_PING_STATS_RESPONSE();
	public OutgoingPacketMeta OUTGOING_PACKET_SEND_ABUSE_REPORT();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ON_NPC();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_4();
	public OutgoingPacketMeta OUTGOING_PACKET_KEY_HELD();
	public OutgoingPacketMeta OUTGOING_PACKET_WALK_DEADMAN();
	public OutgoingPacketMeta OUTGOING_PACKET_JOIN_CLAN();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_ADD_FRIEND();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_BUG_REPORT();
	public OutgoingPacketMeta OUTGOING_PACKET_UNUSED_1();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_EXAMINE();
	public OutgoingPacketMeta OUTGOING_PACKET_FILTER_PUBLIC_CHAT();
	public OutgoingPacketMeta OUTGOING_PACKET_SPACEBAR_CONTINUE();
	public OutgoingPacketMeta OUTGOING_PACKET_MOUSE_IDLE_TICKS();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_6();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_6();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_REGION_UPDATE_RESPONSE();
	public OutgoingPacketMeta OUTGOING_PACKET_GROUND_ITEM_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_WINDOW_MODE_UPDATE();
	public OutgoingPacketMeta OUTGOING_PACKET_KEEP_ALIVE();
	public OutgoingPacketMeta OUTGOING_PACKET_CLAN_RANK();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_TABLE_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_NPC();
	public OutgoingPacketMeta OUTGOING_PACKET_MINIMAP_WALK();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_WIDGET();
	public OutgoingPacketMeta OUTGOING_PACKET_RESUME_DIALOG_OBJECT();
	public OutgoingPacketMeta OUTGOING_PACKET_GROUND_ITEM_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_7();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_3();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_EXAMINE();
	public OutgoingPacketMeta OUTGOING_PACKET_CONSOLE_COMMAND();
	public OutgoingPacketMeta OUTGOING_PACKET_GROUND_ITEM_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_REMOVE_IGNORE();
	public OutgoingPacketMeta OUTGOING_PACKET_FOCUS_CHANGE();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ON_GROUND_ITEM();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_REFLECTION_RESPONSE();
	public OutgoingPacketMeta OUTGOING_PACKET_ADD_IGNORE();
	public OutgoingPacketMeta OUTGOING_PACKET_RESUME_PAUSE();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_GROUND_ITEM();
	public OutgoingPacketMeta OUTGOING_PACKET_OBJECT_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_RESUME_DIALOG_1();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_9();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_2();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_UNUSED_2();
	public OutgoingPacketMeta OUTGOING_PACKET_TABLE_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_REMOVE_FRIEND();
	public OutgoingPacketMeta OUTGOING_PACKET_WALK_HERE();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_7();
	public OutgoingPacketMeta OUTGOING_PACKET_TABLE_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_TABLE_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_MOD_CLIENT_DETECTED();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_10();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_ITEM();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ON_OBJECT();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_PLAYER();
	public OutgoingPacketMeta OUTGOING_PACKET_APPLET_FRAMED();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ON_ITEM();
	public OutgoingPacketMeta OUTGOING_PACKET_DRAG_ITEM();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_5();
	public OutgoingPacketMeta OUTGOING_PACKET_GROUND_ITEM_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_UNUSED_3();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_ACTION_1();
	public OutgoingPacketMeta OUTGOING_PACKET_BUTTON_INPUT();
	public OutgoingPacketMeta OUTGOING_PACKET_TABLE_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ON_PLAYER();
	public OutgoingPacketMeta OUTGOING_PACKET_RESUME_DIALOG_COUNT();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_1();
	public OutgoingPacketMeta OUTGOING_PACKET_BUTTON_CLOSE();
	public OutgoingPacketMeta OUTGOING_PACKET_MOUSE_CLICK();
	public OutgoingPacketMeta OUTGOING_PACKET_MAP_BUILD_COMPLETE();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_5();
	public OutgoingPacketMeta OUTGOING_PACKET_RESUME_DIALOG_2();
	public OutgoingPacketMeta OUTGOING_PACKET_SEND_PRIVATE_MESSAGE();
	public OutgoingPacketMeta OUTGOING_PACKET_GROUND_ITEM_ACTION_4();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_IDLE_LOGOUT();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_SWAP();
	public OutgoingPacketMeta OUTGOING_PACKET_MOUSE_POSITION();
	public OutgoingPacketMeta OUTGOING_PACKET_PLAYER_ACTION_3();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_ACTION_0();
	public OutgoingPacketMeta OUTGOING_PACKET_CAMERA_ROTATION();
	public OutgoingPacketMeta OUTGOING_PACKET_ITEM_EXAMINE();
	public OutgoingPacketMeta OUTGOING_PACKET_IF_BUTTON_8();
	public OutgoingPacketMeta OUTGOING_PACKET_SEND_PUBLIC_MESSAGE();
	public OutgoingPacketMeta OUTGOING_PACKET_SPELL_ON_OBJECT();
	public OutgoingPacketMeta OUTGOING_PACKET_NPC_ACTION_2();
	public OutgoingPacketMeta OUTGOING_PACKET_UPDATE_APPEARANCE();
	public RegionUpdatePacketHeader REMOVE_GROUND_ITEM();
	public RegionUpdatePacketHeader ADD_GROUND_ITEM();
	public RegionUpdatePacketHeader AREA_SOUNDS();
	public RegionUpdatePacketHeader ADD_PENDING_SPAWN();
	public RegionUpdatePacketHeader ADD_PROJECTILE();
	public RegionUpdatePacketHeader ANIMATE_OBJECT();
	public RegionUpdatePacketHeader REMOVE_PENDING_SPAWN();
	public RegionUpdatePacketHeader PERFORM_LOC_GRAPHIC();
	public RegionUpdatePacketHeader ADD_INTERACTABLE();
	public RegionUpdatePacketHeader UPDATE_GROUND_ITEM();
	public IncomingPacketMeta INCOMING_PACKET_SET_WIDGET_ITEMS();
	public IncomingPacketMeta INCOMING_PACKET_PRIVATE_MESSAGE();
	public IncomingPacketMeta INCOMING_PACKET_LOC_ANIM();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_CLAN_CHAT();
	public IncomingPacketMeta INCOMING_PACKET_REBUILD_NORMAL();
	public IncomingPacketMeta INCOMING_PACKET_SET_WIDGET_MODEL();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_ZONE_PARTIAL_FOLLOWS();
	public IncomingPacketMeta INCOMING_PACKET_CAM_LOOK_AT();
	public IncomingPacketMeta INCOMING_PACKET_MIDI_JINGLE();
	public IncomingPacketMeta INCOMING_PACKET_MAP_PROJ();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_ZONE_PARTIAL_ENCLOSED();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_EXCHANGE_OFFERS();
	public IncomingPacketMeta INCOMING_PACKET_LOC_DEL();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_STAT();
	public IncomingPacketMeta INCOMING_PACKET_SET_EVENTS();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_PLAYER_WEIGHT();
	public IncomingPacketMeta INCOMING_PACKET_LOGOUT_FULL();
	public IncomingPacketMeta INCOMING_PACKET_SET_POSITION();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_INVENTORY_STOP_TRANSMIT();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_ZONE_FULL_FOLLOWS();
	public IncomingPacketMeta INCOMING_PACKET_LOC_ADD();
	public IncomingPacketMeta INCOMING_PACKET_OPEN_SUB();
	public IncomingPacketMeta INCOMING_PACKET_REFLECTION_CHECK();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_DESTINATION();
	public IncomingPacketMeta INCOMING_PACKET_OPEN_TOP();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_INVENTORY_PARTIAL();
	public IncomingPacketMeta INCOMING_PACKET_OBJ_DEL();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_CLAN_CHAT_SINGLE_USER();
	public IncomingPacketMeta INCOMING_PACKET_SYNTH_SOUND();
	public IncomingPacketMeta INCOMING_PACKET_NPC_INFO_SMALL();
	public IncomingPacketMeta INCOMING_PACKET_GAME_MESSAGE();
	public IncomingPacketMeta INCOMING_PACKET_CAM_SHAKE();
	public IncomingPacketMeta INCOMING_PACKET_LOGOUT_TRANSFER();
	public IncomingPacketMeta INCOMING_PACKET_OBJ_COUNT();
	public IncomingPacketMeta INCOMING_PACKET_PLAYER_INFO();
	public IncomingPacketMeta INCOMING_PACKET_SET_TEXT();
	public IncomingPacketMeta INCOMING_PACKET_SET_COLOR();
	public IncomingPacketMeta INCOMING_PACKET_SET_ANGLE();
	public IncomingPacketMeta INCOMING_PACKET_RESET_CLIENT_VARCACHE();
	public IncomingPacketMeta INCOMING_PACKET_PING_STATISTICS_REQUEST();
	public IncomingPacketMeta INCOMING_PACKET_SYNC_CLIENT_VARCACHE();
	public IncomingPacketMeta INCOMING_PACKET_SOUND_AREA();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_WIDGETS();
	public IncomingPacketMeta INCOMING_PACKET_VARP_LARGE();
	public IncomingPacketMeta INCOMING_PACKET_UNKNOWN_3();
	public IncomingPacketMeta INCOMING_PACKET_FRIENDS_CHAT_MESSAGE();
	public IncomingPacketMeta INCOMING_PACKET_MOVE_SUB();
	public IncomingPacketMeta INCOMING_PACKET_SET_ANIMATION();
	public IncomingPacketMeta INCOMING_PACKET_SET_OBJECT();
	public IncomingPacketMeta INCOMING_PACKET_RESET_ANIMS();
	public IncomingPacketMeta INCOMING_PACKET_URL_OPEN();
	public IncomingPacketMeta INCOMING_PACKET_SET_PRIVATE_CHAT_FILTER();
	public IncomingPacketMeta INCOMING_PACKET_SET_PLAYER_OP();
	public IncomingPacketMeta INCOMING_PACKET_OBJ_ADD();
	public IncomingPacketMeta INCOMING_PACKET_SET_CHAT_FILTER();
	public IncomingPacketMeta INCOMING_PACKET_EXCHANGE_HISTORY();
	public IncomingPacketMeta INCOMING_PACKET_TRIGGER_ON_DIALOG_ABORT();
	public IncomingPacketMeta INCOMING_PACKET_PRIVATE_MESSAGE_ECHO();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_FRIENDS_LIST();
	public IncomingPacketMeta INCOMING_PACKET_VARP_SMALL();
	public IncomingPacketMeta INCOMING_PACKET_CLOSE_SUB();
	public IncomingPacketMeta INCOMING_PACKET_OCULUS_ORB_TOGGLE();
	public IncomingPacketMeta INCOMING_PACKET_DISCONNECTED();
	public IncomingPacketMeta INCOMING_PACKET_SET_NPC_HEAD();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_IGNORE_LIST();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_PLAYER_ENERGY();
	public IncomingPacketMeta INCOMING_PACKET_MAP_ANIM();
	public IncomingPacketMeta INCOMING_PACKET_MIDI_SONG();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_REBOOT_TIMER();
	public IncomingPacketMeta INCOMING_PACKET_MINIMAP_TOGGLE();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_INVENTORY_FULL();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_SITE_SETTINGS();
	public IncomingPacketMeta INCOMING_PACKET_OCULUS_ORB_ON();
	public IncomingPacketMeta INCOMING_PACKET_LOC_GRAPHIC();
	public IncomingPacketMeta INCOMING_PACKET_HINT_ARROW();
	public IncomingPacketMeta INCOMING_PACKET_FRIENDS_LIST_LOADED();
	public IncomingPacketMeta INCOMING_PACKET_SET_SCROLL_POSITION();
	public IncomingPacketMeta INCOMING_PACKET_SET_PLAYER_CHATHEAD();
	public IncomingPacketMeta INCOMING_PACKET_NPC_INFO_LARGE();
	public IncomingPacketMeta INCOMING_PACKET_RUN_CLIENTSCRIPT();
	public IncomingPacketMeta INCOMING_PACKET_SET_WIDGET_MODEL_ROTATION();
	public IncomingPacketMeta INCOMING_PACKET_UPDATE_UID();
	public IncomingPacketMeta INCOMING_PACKET_REBUILD_REGION();
	public IncomingPacketMeta INCOMING_PACKET_CAM_RESET();
	public IncomingPacketMeta INCOMING_PACKET_CAM_MOVE_TO();
	public IncomingPacketMeta INCOMING_PACKET_SET_HIDE();
	public AbstractSocket gameConnectionSocket();
	public AbstractSocket lastConnectionSocket();
	public PacketContext gameConnection();
	public AbstractArchive objectDefinitionFileSystem();
	public AbstractArchive objectDefinitionModelFileSystem();
	public AbstractArchive animationSkeletonFileSystem();
	public AbstractArchive widgetModelFileSystem();
	public AbstractArchive npcModelFileSystem();
	public AbstractArchive npcDefinitionFileSystem();
	public AbstractArchive combatBarSpriteFileSystem();
	public AbstractArchive varPlayerTypeFileSystem();
	public AbstractArchive identityKitNodeFileSystem();
	public AbstractArchive inventoryDefinitionFileSystem();
	public AbstractArchive spotAnimModelFileSystem();
	public AbstractArchive spotAnimFileSystem();
	public AbstractArchive animationSequenceFileSystem();
	public AbstractArchive animationSkinFileSystem();
	public AbstractArchive grandExchangeItemFileSystem();
	public AbstractArchive itemDefinitionFileSystem();
	public AccessFileHandler idx255FileHandler();
	public AccessFileHandler dat2FileHandler();
	public AccessFileHandler randomDatFileHandler();
	public AccessFileHandler[] indexFileHandlers();
	public Resampler resampler();
	public Task loginConnectionTask();
	public Task gameConnectionTask();
	public Signlink taskManager();
	public Deque widgetTimerScriptEventDeque();
	public Deque mouseReleaseScriptEventDeque();
	public Deque mouseClickScriptEventDeque();
	public Deque[][][] itemPileDeque();
	public Deque pendingSpawnDeque();
	public Deque animableObjectDeque();
	public Deque projectileDeque();
	public Deque fileSystemRequestDeque();
	public Deque fileSystemResponseDeque();
	public Deque drawnTileDeque();
	public Deque areaSoundEmitterDeque();
	public MouseTracker mouseTracker();
	public CollisionMap[] collisionMaps();
	public AudioEffect[] audioEffects();
	public Npc[] npcs();
	public ChatSetting CHAT_SETTING_PUBLIC();
	public ChatSetting CHAT_SETTING_OFF();
	public ChatSetting CHAT_SETTING_PRIVATE();
	public Player[] players();
	public Player localPlayer();
	public MenuRowContext topMenuRowContext();
	public AttackOptionSetting npcAttackOptionSetting();
	public AttackOptionSetting playerAttackOptionSetting();
	public GrandExchangeOffer[] exchangeOffers();
	public MouseListener mouseListener();
	public KeyboardListener keyboardListener();
	public Region region();
	public Widget pleaseWaitWidget();
	public Widget mouseCrosshairWidget();
	public Widget[] cachedWidgets();
	public Widget[][] widgets();
	public RuneScriptVM runescriptVM();
	public Server[] servers();
	public RSShadowedFont fontBold12pt();
	public RSShadowedFont fontPlain12pt();
	public RSShadowedFont fontPlain11pt();
	public RSShadowedFont itemAmountFont();
	public AudioRunnable audioRunnable();
	public FriendManager friendManager();
	public ClanContainer clanContainer();
	public Occluder[] regionOccluders();
	public Occluder[][] loadedOccluders();
	public PlatformInfo platformInfo();
	public Client clientInstance();
	public boolean clientFocused();
	public int itemSelectionState();
	public java.lang.String[] menuTargets();
	public int[] menuOpcodes();
	public int[] menuTertiaryArgs();
	public int[] menuSecondaryArgs();
	public java.lang.String[] menuActions();
	public boolean[] menuShiftClickActions();
	public int rootWidgetIndex();
	public int playerWeight();
	public int runEnergy();
	public int[] widgetWidths();
	public int[] widgetPositionsY();
	public int redrawMode();
	public int[] widgetHeights();
	public int[] widgetPositionsX();
	public boolean resizeMode();
	public int mapRotation();
	public int mouseCrosshairState();
	public boolean[] playerActionPriorities();
	public boolean menuOpen();
	public int[] currentSkillLevels();
	public int[] skillExperiences();
	public int[] absoluteSkillLevels();
	public java.lang.String[] playerActions();
	public int[] mapRegionIDs();
	public int menuItemCount();
	public int menuHeight();
	public int menuWidth();
	public int menuY();
	public int menuX();
	public int[] menuPrimaryArgs();
	public boolean spellSelected();
	public int drawingAreaTop();
	public int drawingAreaBottom();
	public int[] drawingAreaPixels();
	public int drawingAreaHeight();
	public int drawingAreaWidth();
	public int tradeChatMode();
	public int publicChatMode();
	public int audioEffectCount();
	public boolean cameraLocked();
	public int mapState();
	public int viewportHeight();
	public int viewportWidth();
	public int bootState();
	public java.util.HashMap fontHashMap();
	public int[] npcIndices();
	public int[][][] regionHashes();
	public boolean inInstancedScene();
	public int currentWorld();
	public boolean membersWorld();
	public int currentWorldMask();
	public int gameCycle();
	public int hintArrowType();
	public int hintArrowX();
	public int hintArrowY();
	public int hintArrowSubY();
	public int hintArrowSubX();
	public int hintArrowHeight();
	public int hintArrowNpcIndex();
	public int hintArrowPlayerIndex();
	public short[] exchangeSearchResults();
	public int canvasWidth();
	public byte[][] xteaByteArray1();
	public int lastMouseButton();
	public int currentMouseButton();
	public long lastMouseMoveTime();
	public int pendingMouseClickY();
	public int pendingMouseX();
	public int pendingMouseClickX();
	public int mouseIdleTicks();
	public long lastMouseClickTime();
	public int pendingMouseY();
	public int mouseY();
	public int mouseX();
	public byte[][] xteaByteArray2();
	public int lastSelectedItemIndex();
	public int selectedRegionTileX();
	public boolean viewportWalking();
	public int selectedRegionTileY();
	public int[] landscapeIndices();
	public int[][][] tileHeights();
	public byte[][][] sceneRenderRules();
	public int[] regionArchiveIDs();
	public int spellTargetFlags();
	public int canvasHeight();
	public int currentPlane();
	public java.util.Map chatboxChannelMap();
	//public long[] onCursorUIDs();
	public int onCursorUIDCount();
	public java.lang.String loginMessage3();
	public java.lang.String loginMessage2();
	public java.lang.String loginMessage1();
	public int loginState();
	public String username();
	public String password();
	public int gameState();
	public java.lang.String currentDomain();
	public java.lang.String authenticatorPin();
	public int mapBaseX();
	public int buildVersion();
	public int mapBaseY();
	public int[] varps();
	public int[] tempVarps();
	public char[] asciiExtentions();
	public int[] playerIndices();
	public int playerCount();
	public int[][] xteaKeys();
	public boolean loadMembersItemDefinitions();
	public int cameraX();
	public int cameraZ();
	public int cameraY();
	public int cameraPitch();
	public int cameraYaw();
	public int viewportScale();
	public int destinationX();
	public int destinationY();
	public Sprite[] worldSpriteBackground();
	public IndexedImage worldIndexImageRightArrow();
	public IndexedImage[] worldIndexImageArrows();
	public IndexedImage worldIndexImageLeftArrow();
	public IndexedImage[] worldIndexImageFlags();
	public IndexedImage[] worldIndexImageStars();
	public Cache varpbitCache();
	public boolean loginWorldSelectorOpen();
	public int centerLoginScreenX();
	public Archive regionArchive();

	public boolean getDisableRenderingState();
	public void setDisableRenderingState();
	
	public void invokeAddChatMessage(int channel, String name, String message, String sender, int predicate);
	public org.osrs.api.wrappers.Sprite invokeGetItemSprite(int a, int b, int c, int d, int e, boolean f, int i);
	public int invokeGetVarp(int var, int predicate);
	public void invokeSetWorld(Server a, int b);
	public void invokeSetGameState(int a, int b);
	public ObjectDefinition invokeGetObjectDefinition(int a, int b);
	public AnimationSequence invokeGetAnimationSequence(int a, int b);
	public ItemDefinition invokeGetItemDefinition(int a, int b);
	public NPCDefinition invokeGetNPCDefinition(int a, int b);
	public Hitsplat invokeGetHitsplatDefinition(int a, int b);
	public SpotAnim invokeGetSpotAnim(int a, int b);
	public void invokeWorldToScreen(int a, int b, int c, int d);
	public int invokeGetTileHeight(int a, int b, int c, int d);
	public void invokeFireScriptEvent(ScriptEvent a, int b);
	public void invokeShutdownClient(int a);
	public OutgoingPacket invokeCreateOutgoingPacket(OutgoingPacketMeta a, ISAACCipher b, byte c);
	public DefinitionProperty invokeGetDefinitionProperty(int a, int b);
	

	public void invokeProcessAction(int a, int b, int c, int d, String e, String f, int g, int h, int i);
	public void overrideProcessAction(int a, int b, int c, int d, String e, String f, int g, int h);
	public void turnOffProcessActionOverride();
	public boolean overridingProcessAction();
	public int getSubDoActionArgA();
	public int getSubDoActionArgB();
	public int getSubDoActionArgC();
	public int getSubDoActionArgD();
	public String getSubDoActionArgE();
	public String getSubDoActionArgF();
	public int getSubDoActionArgG();
	public int getSubDoActionArgH();
	public void setHighAlchMode(boolean enable);
	public boolean isHighAlchModeEnabled();
	public void setUsername(String name);
	public void setPassword(String pass);
	public boolean invokeLoadWorlds(int a);
	public void setLoginMessages(String a, String b, String c);
	public void setLoginState(int state);
	public void setMenu(boolean state);
	public byte[] randomDatData();
	public ArrayList<MenuAction> getSessionTrackedActions();
	public ArrayList<Point> getSessionTrackedClicks();
	public void addSessionClick(int x, int y);
	public void addSessionAction(MenuAction action);
	public void setSelectedRegionTileX(int localX);
	public void setSelectedRegionTileY(int localY);
	public void setViewportWalking(boolean flag);
	public void runScript(Object[] args, int b);
	public boolean awtFocusCheck();
	public boolean awtFocusCheck2();
	public void ignoreNextOpenMenuRequest();
	public void writeWalkTileMinimap(org.osrs.api.wrappers.ByteBuffer buffer, int tileX, int tileY, int relativeScreenX, int relativeScreenY);
	public void setDestinationX(int destX);
	public void setDestinationY(int destY);
	public int widgetVisibleCycle();
	
}